### ISSUE TITLE
Update django app installation guide

### ISSUE THREAD

**Issue by iriahi** [ahmia/search#11]
We should update the following install guide: https://github.com/juhanurmi/ahmia/blob/master/README.md
Should we target the latest Ubuntu LTS and Fedora?

**Comment by juhanurmi** [comment]
Yes, we should update the installation guide for Ubuntu and Fedora.

**Comment by iriahi** [comment]
By the way, this is a duplicate of https://github.com/ahmia/search/issues/2

**Comment by iriahi** [comment]
I think this is ready.
I close this issue, even if we need to update documentation continuously.
