### ISSUE TITLE
Evaluate repositories organization

### ISSUE THREAD

**Issue by iriahi** [ahmia/search#13]
I'm thinking of the following structure:
ahmia/ <- Org name
  ahmia <- Repository containing the django app of ahmia.fi, documentation on how to install it and how to run it (with apache, nginx config samples)
  onion-elastic-bot <- Crawler and install guide

I'm open to suggestions. Is the tools directory still used?

**Comment by juhanurmi** [comment]
Looks great! Yes, tools are useful although some of them are old and not usable anymore.

**Comment by iriahi** [comment]
I created two repositories:
https://github.com/iriahi/ahmia-site and https://github.com/iriahi/ahmia-elasticbot
I will add/edit a README soon enough. 
As you can see, these repositories have kept their respective commit history.

**Comment by iriahi** [comment]
For reference: I created [https://github.com/iriahi/ahmia-index](https://github.com/iriahi/ahmia-index)

The 3 repositories have been transfered to [Ahmia](https://github.com/ahmia/).
The only thing missing is the tools directory but I think we are going to use the code in ahmia-crawler.

I consider this task done.
